name: YntymakAppMVP
description: "Yntymak App"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.10.1

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  shared_preferences: ^2.5.4
  provider: ^6.1.5+1
  url_launcher: ^6.3.2
  http: ^1.6.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  # ДОБАВИЛИ СЮДА:
  flutter_launcher_icons: ^0.13.1

flutter:
  uses-material-design: true
  assets:
    - assets/images/logo.png
    - assets/images/app_logo.png
    - assets/images/onboarding_first.png
    - assets/images/onboarding_second.png
    - assets/images/onboarding_third.png

# НАСТРОЙКИ ИКОНКИ (В САМОМ КОНЦЕ ФАЙЛА)
flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/app_logo.png" # Твой основной логотип
  min_sdk_android: 21
  adaptive_icon_background: "#F8FFF8" # Цвет фона для Android (под твой дизайн)
  adaptive_icon_foreground: "assets/images/app_logo.png" # Само лого